#!/usr/bin/env python3
"""Generate the docs pages that must never drift from the code.

Produces two files:
  docs/reference/commands.md    every command, option, and exit code, from the CLI
  docs/concepts/safety-model.md the state table and the policy table, from the code

The state table comes from the Classification enum plus CLASSIFICATION_HELP. The
policy table is built by running the real decide_* functions over one synthetic
snapshot per classification, so the documented behavior is literally the tested
behavior. No git and no I/O beyond writing the two files.

Usage:
    python scripts/gen_docs.py            # write the files
    python scripts/gen_docs.py --check    # exit 1 if they are stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Typer vendors click; import the Context class from there rather than depending on
# a separately installed click, and duck-type params instead of isinstance checks.
from typer._click import Context as ClickContext  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src"
sys.path.insert(0, str(SRC))

from repo_manager import __version__  # noqa: E402
from repo_manager.cli import app  # noqa: E402
from repo_manager.models import (  # noqa: E402
    CLASSIFICATION_HELP,
    Checkout,
    Classification,
    Identity,
    InProgressOperation,
    InferenceSource,
    Operation,
    RemoteState,
    Relationship,
    RepositorySnapshot,
    Verdict,
    Worktree,
)
from repo_manager import policy  # noqa: E402

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_docs.py. Do not edit by hand; "
    "run `python scripts/gen_docs.py` and commit the result. -->\n"
)


# -- command reference --------------------------------------------------------------


def _render_command(name: str, cmd) -> str:
    lines: list[str] = [f"### `{name}`\n"]
    help_text = (cmd.help or cmd.short_help or "").strip()
    if help_text:
        lines.append(help_text + "\n")

    ctx = ClickContext(cmd, info_name=name)
    usage = cmd.collect_usage_pieces(ctx)
    lines.append("```")
    lines.append(f"repo-manager {name} {' '.join(usage)}".rstrip())
    lines.append("```\n")

    rows = []
    for param in cmd.get_params(ctx):
        if getattr(param, "param_type_name", "") != "option":
            continue
        if getattr(param, "hidden", False):
            continue
        opts = ", ".join(f"`{o}`" for o in param.opts)
        default = ""
        if param.default not in (None, False):
            default = f" (default: `{param.default}`)"
        rows.append((opts, ((param.help or "") + default).strip()))

    if rows:
        lines.append("| Option | Description |")
        lines.append("| --- | --- |")
        for opts, desc in rows:
            lines.append(f"| {opts} | {desc} |")
        lines.append("")
    return "\n".join(lines)


def render_commands() -> str:
    from typer.main import get_command

    click_app = get_command(app)

    out = [GENERATED_NOTE, "# Command reference\n"]
    out.append(f"Generated from repo-manager `{__version__}`.\n")

    commands = click_app.commands  # type: ignore[attr-defined]
    for name in sorted(commands):
        cmd = commands[name]
        if getattr(cmd, "hidden", False):
            continue
        out.append(_render_command(name, cmd))

    out.append("## Exit codes\n")
    out.append("| Code | Meaning |")
    out.append("| --- | --- |")
    out.append("| 0 | All requested operations completed or were already current. |")
    out.append("| 1 | One or more repositories failed. |")
    out.append("| 2 | Invalid command, configuration, or selection. |")
    out.append("| 3 | One or more operations were safety-skipped (see `--ignore-skips`). |")
    out.append("")
    return "\n".join(out)


# -- safety model -------------------------------------------------------------------


def _synthetic(classification: Classification) -> RepositorySnapshot:
    """A minimal snapshot that a given classification would produce.

    Only the fields the policy functions read are populated. This lets the real
    decide_* functions run without building git fixtures.
    """
    identity = Identity(
        name="example", absolute_path="/w/example", relative_path="example",
        remote_name="origin",
    )
    checkout = Checkout(
        head_sha="0" * 40,
        current_branch="main",
        upstream_branch="origin/main",
        default_branch="main",
        default_branch_inference_source=InferenceSource.REMOTE_HEAD,
    )
    worktree = Worktree()
    remote = RemoteState(relationship=Relationship.CURRENT, ahead_count=0, behind_count=0)

    c = classification
    if c is Classification.READY:
        remote.relationship = Relationship.BEHIND
        remote.behind_count = 2
    elif c is Classification.DIRTY:
        worktree.unstaged_count = 1
        remote.relationship = Relationship.BEHIND
        remote.behind_count = 1
    elif c is Classification.IN_PROGRESS:
        worktree.in_progress_operation = InProgressOperation.REBASE
        checkout.current_branch = None
        checkout.upstream_branch = None
    elif c is Classification.DETACHED:
        checkout.current_branch = None
        checkout.detached_sha = "0" * 40
        checkout.upstream_branch = None
        remote.relationship = Relationship.UNKNOWN
    elif c is Classification.NO_UPSTREAM:
        checkout.upstream_branch = None
        remote.relationship = Relationship.UNKNOWN
    elif c is Classification.DEFAULT_BRANCH_UNKNOWN:
        checkout.default_branch = None
        checkout.default_branch_inference_source = InferenceSource.AMBIGUOUS
    elif c is Classification.AMBIGUOUS_REMOTE:
        identity.remote_name = None
    elif c is Classification.AHEAD:
        remote.relationship = Relationship.AHEAD
        remote.ahead_count = 1
    elif c is Classification.DIVERGED:
        remote.relationship = Relationship.DIVERGED
        remote.ahead_count = 1
        remote.behind_count = 1
    elif c is Classification.REMOTE_UNAVAILABLE:
        remote.relationship = Relationship.UNKNOWN

    return RepositorySnapshot(
        identity=identity, checkout=checkout, worktree=worktree,
        remote=remote, classification=c,
    )


def _verdict_cell(v: Verdict) -> str:
    return "proceed" if v is Verdict.PROCEED else "skip"


def render_safety_model() -> str:
    out = [GENERATED_NOTE, "# Safety model\n"]
    out.append(
        "Every repository is reduced to exactly one **state**. Each operation then "
        "decides, per state, whether it may proceed or must skip with a reason.\n"
    )

    out.append("## Repository states\n")
    out.append("| State | Meaning |")
    out.append("| --- | --- |")
    for c in Classification:
        out.append(f"| `{c.value}` | {CLASSIFICATION_HELP[c.value]} |")
    out.append("")

    out.append("## Policy by operation\n")
    out.append(
        "Generated by running the real decision functions over one representative "
        "snapshot per state.\n"
    )
    out.append("| State | `update` | `switch-default` | `checkout` |")
    out.append("| --- | --- | --- | --- |")
    for c in Classification:
        snap = _synthetic(c)
        u = _verdict_cell(policy.decide_update(snap).verdict)
        s = _verdict_cell(policy.decide_switch_default(snap).verdict)
        # Checkout to the default branch, assumed present locally.
        co = _verdict_cell(
            policy.decide_checkout(snap, snap.checkout.default_branch or "main", True, True).verdict
        )
        out.append(f"| `{c.value}` | {u} | {s} | {co} |")
    out.append("")
    out.append(
        "> `checkout` is permissive by design: it only pre-skips an in-progress "
        "repository and a branch that exists nowhere. A dirty tree that would be "
        "overwritten is refused by git itself and reported as a failure.\n"
    )
    return "\n".join(out)


# -- driver -------------------------------------------------------------------------

TARGETS = {
    REPO_ROOT / "docs" / "reference" / "commands.md": render_commands,
    REPO_ROOT / "docs" / "concepts" / "safety-model.md": render_safety_model,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if files are stale")
    args = parser.parse_args()

    stale = []
    for path, render in TARGETS.items():
        content = render().rstrip() + "\n"
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check and stale:
        print("STALE generated docs (run `python scripts/gen_docs.py`):", file=sys.stderr)
        for p in stale:
            print(f"  {p.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    if args.check:
        print("generated docs are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
